---
authors:
  - Ansible Network Community (ansible-network)
dependencies:
  "ansible.netcommon": "*"
license_file: LICENSE
name: iosxr
namespace: cisco
readme: README.rst
repository: https://github.com/ansible-collections/iosxr
tags: [cisco, iosxr, networking, netconf]
